name: fluttercraft_launcher
description: A flutter implementation of Minecraft Launcher.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  window_manager: ^0.4.3
  protocol_handler: ^0.2.0
  json_annotation: ^4.9.0
  go_router: ^14.6.3
  flutter_bloc: ^9.0.0
  uuid: ^4.5.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  path: ^1.9.0
  http: ^1.2.2
  crypto: ^3.0.6


dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/
